### ISSUE TITLE
The example reveals problems.

### ISSUE THREAD

**Issue by dschalk** [Tixit/observe#2]
After putting "&&" between the boolean tests, adding a ")", and putting ".c" between "subject" and "slice", I got the example to run in the browser.

The calls to "set" all worked, as did "push" and "splice".  The status of the "c" array is printed below under the example output. As you can see, pushing 3 and 4 succeeded, but the report stated, "My c property got 1 new value: 3. Similarly, the call to "append" succeeded, but the report said, "My c property got 3 new values: 5,6."

Here is the output from my console log:
```
My 'a' property changed to: 2.
FINALLY someone sets my b.x property!
[]
My c property got 1 new value: 3.
[3, 4]
Someone took 3 from c!
 [4]
 Well i just don't know *what's* going on with b.y.
[4]
My c property got 3 new values: 5,6.
 [4, 5, 6, 7]
```

**Comment by fresheneesz** [comment]
Published 1.1.3 that fixes a bug I found while fixing the readme. Thanks for the notes!

**Comment by dschalk** [comment]
You're welcome. I appreciate what you are doing, and since you are 
still interested in maintaining and improving "observer", I will 
incorporate it in one of my projects and report things that might 
interest you.

I need observer functionality, and I don't need all the baggage and 
opinionated constraints that come with most libraries. I'm sure I'm not 
alone in this position. You are making a valuable contribution and I 
thank you for it.

**Comment by fresheneesz** [comment]
@dschalk Well thank you for saying so! If you think its a solid module, feel free to star it! And let me know if you have any other issues or questions.
