### ISSUE TITLE
Missing version number for proto dependency

### ISSUE THREAD

**Issue by tony99nyr** [Tixit/observe#5]
Because there is no version specified for `proto`, `npm shrinkwrap` can fail or get confused when trying to use the `observe` library.

`"dependencies": {
    "proto": ""
  },`

npm WARN saveError Problems were encountered
npm WARN saveError Please correct and try again.
npm WARN saveError invalid: have proto@1.0.11 (expected: )

**Comment by fresheneesz** [comment]
Ah, yeah, npm changed what a blank string means there for no good reason. I'll change it to "*"

**Comment by fresheneesz** [comment]
Fixed and published on v1.3.7 https://github.com/Tixit/observe/commit/bed3124634b4f83a314fb2f1ba79bc1ba7bba391
